# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/Layers.ipynb.

# %% auto 0
__all__ = ['keras_package', 'dummy']

# %% ../../../nbs/Layers.ipynb 1
import tensorflow as tf

from ..._components.mono_dense_layer import MonoDense

# %% ../../../nbs/Layers.ipynb 4
def dummy() -> None:
    pass


dummy.__module__ = "_dummy"

# %% ../../../nbs/Layers.ipynb 5
__all__ = ["MonoDense"]

# %% ../../../nbs/Layers.ipynb 7
keras_package = "airt.keras.layers"

# %% ../../../nbs/Layers.ipynb 9
if tf.keras.saving.get_registered_object(f"{keras_package}>MonoDense") == None:
    try:
        tf.keras.utils.register_keras_serializable(keras_package)(MonoDense)
        raise ValueError("s")
    except Exception as e:
        print(f"Exception ignored: {e}")
