__version__ = "0.3.2"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/TopLevel.ipynb.

# %% auto 0
__all__ = ['dummy']

# %% ../nbs/TopLevel.ipynb 1
from pkgutil import extend_path

# %% ../nbs/TopLevel.ipynb 2
if "__path__" in globals():
    __path__ = extend_path(__path__, __name__)

# %% ../nbs/TopLevel.ipynb 3
def dummy() -> None:
    pass

# %% ../nbs/TopLevel.ipynb 4
del dummy

__all__ = []
