name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Install
        run: pip install --pre -e ".[test]"
      - name: Test
        run: pytest -v
